version: '3'

services:
  front:
    container_name: front
    image: easydocker/front
    ports:
      - "${FRONT_PORT}:80"

  api:
    container_name: api
    image: easydocker/api
    volumes:
      - ./.env:/app/.env
    ports:
      - "${API_PORT}:3000"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
