FROM node:18-alpine as build
ARG VITE_API_URL=https://localhost:8000

WORKDIR /usr/app

COPY package.json yarn.lock .
RUN yarn install

COPY . .
RUN echo VITE_API_URL=$VITE_API_URL >> .env
RUN cat .env
RUN yarn build

FROM nginx:1.25-alpine

COPY ./.docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/build /usr/share/nginx/html
