name: api-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        run: go install github.com/swaggo/swag/cmd/swag@latest && swagger init -g src/server.go
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: api