name: FRONT - Build and publish

on:
  push:
    branches:
      - main
      - dockerize-application

env:
  GITHUB_CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/front

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish Docker image
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against the docker registries
      # https://github.com/docker/login-action
      - name: Log into the Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest
          labels: |
            org.opencontainers.image.description=${{ github.event.head_commit.message }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "./front"
          file: "./front/Dockerfile.prod"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max