name: Check test

on:
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  NODE_VERSION: 16

jobs:
    api-test:
        name: API Test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.20'

          - name: Test
            working-directory: api
            run: go test -v ./...

    front-test:
        name: Front Test
        runs-on: ubuntu-latest
        steps:
          - name: Install NodeJS
            uses: actions/setup-node@v2
            with:
              node-version: ${{ env.NODE_VERSION }}

          - name: Code Checkout
            uses: actions/checkout@v2

          - name: Install Dependencies
            working-directory: front
            run: yarn install

          - name: Code Testing
            working-directory: front
            run: yarn test
